FROM alpine:3.17

RUN apk add --no-cache sqlite

RUN mkdir -p /data /scripts

WORKDIR /scripts

COPY create-database.sql populate-database.sql ./

VOLUME /data

CMD ["sh", "-c", "sqlite3 /data/inventory.db '.read /scripts/create-database.sql' && \
                   sqlite3 /data/inventory.db '.read /scripts/populate-database.sql' && \
                   tail -f /dev/null"]
