services:
  database:
    build:
      context: ./DatabaseDocker
      dockerfile: Dockerfile.SQLite
    container_name: inventory-db
    volumes:
      - db_data:/data   # Banco persistente interno ao container
    networks:
      - app-network
    environment:
      - DB_PATH=/data/inventory.db

  app:
    build:
      context: .
      dockerfile: AppDocker/Dockerfile.App
    container_name: inventory-app
    depends_on:
      - database
    ports:
      - "${APP_PORT}:5019"  # Porta configuravel no .env
    environment:
      - APP_PORT=${APP_PORT}  # Porta configuravel via .env
      - DB_PATH=/data/inventory.db  # Caminho do banco configurado no container
    volumes:
      - db_data:/data   # Compartilha o volume com o banco
    networks:
      - app-network

volumes:
  db_data:  # Volume para persistir o banco de dados

networks:
  app-network:
    driver: bridge
