version: '3.8'

services:
  database:
    build:
      context: ./DatabaseDocker
      dockerfile: Dockerfile.SQLite
    container_name: inventory-db
    volumes:
      - db_data:/data
    networks:
      - app-network

  app:
    build:
      context: ./AppDocker
      dockerfile: Dockerfile.App
    container_name: inventory-app
    depends_on:
      - database
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/data/inventory.db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
