services:
  database:
    build:
      context: ./DatabaseDocker
      dockerfile: Dockerfile.SQLite
    container_name: inventory-db
    volumes:
      - db_data:/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: AppDocker/Dockerfile.App
    container_name: inventory-app
    depends_on:
      - database
    ports:
      - "${APP_PORT}:5019"      
    environment:
      - APP_PORT=${APP_PORT}
      - DB_PATH=${DB_PATH}
    volumes:
      - ./data:/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
