services:
  database:
    build:
      context: ./DatabaseDocker
      dockerfile: Dockerfile.SQLites
    container_name: inventory-db
    volumes:
      - db_data:/data
    networks:
      - app-network
    environment:
      - DB_PATH=/data/inventory.db

  app:
    build:
      context: .
      dockerfile: AppDocker/Dockerfile.App
    container_name: inventory-app
    depends_on:
      - database
    ports:
      - "${APP_PORT}:5019"
    environment:
      - APP_PORT=${APP_PORT}
      - DB_PATH=/data/inventory.db
    volumes:
      - db_data:/data 
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
